# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e38e03fe84c487c25a99c80fe02c85db4b972d49b48524eebec1ed49471e8b8057cb9d68d8a92e24b6aeadc3e1cb90b7abd6ddb3de1d7d62018197aaa1e5cce

test:
  secret_key_base: b38e81ee32916ff965a65576e42dfe74b22d04b450e682e0801ac956a4fe148a06ab1fcdbeb4dc1c9344368d4979e74830e6ed365ae0d475f5f2ce130d98f9c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
